//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kladmen
{
    using System;
    using System.Collections.Generic;
    
    public partial class stroymat
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Ed_izm { get; set; }
        public Nullable<double> Ostatok { get; set; }
        public Nullable<int> ID_Sklad { get; set; }
    
        public virtual Sklad Sklad { get; set; }
    }
}
